# fly.toml app configuration file generated for brophy-org on 2023-10-20T09:54:09-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "brophy-org"
primary_region = "iad"

[build]

[[services]]
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"
  auto_start_machines = true
  auto_stop_machines = true
  min_machines_running = 1

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "5s"
    interval = "60s"
    timeout = "5s"
